export const ADD_TODO = 'ADD_TODO'
export const EDIT_POPUP_OPEN = 'EDIT_POPUP_OPEN'
export const EDIT_POPUP_CLOSE = 'EDIT_POPUP_CLOSE'
export const EDIT_TODO = 'EDIT_TODO'
export const OPEN_DIALOG = 'OPEN_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'